### ISSUE TITLE
ERROR: Unable to resolve dependency for ':app@devDebug/compileClasspath': Could not resolve com.mapspeople.mapsindoors:mapsindoorssdk:3.3.1.

### ISSUE THREAD

**Issue by NimaaZx** [MapsIndoors/MapsIndoorsAndroid-Demo-Samples#2]
Hello @namine92  . when i want to compile or rebuild app , I get this Error:

ERROR: Unable to resolve dependency for ':app@devDebug/compileClasspath': Could not resolve com.mapspeople.mapsindoors:mapsindoorssdk:3.3.1.

Then I changed  :     implementation 'com.mapspeople.mapsindoors:mapsindoorssdk:3.3.1@aar'
to  :      implementation 'com.mapspeople.mapsindoors:mapsindoorssdk:{{%3.3.1%}}@aar'
but nothing has changed.

full form of error:

> ERROR: Unable to resolve dependency for ':app@devDebug/compileClasspath': Could not resolve com.mapspeople.mapsindoors:mapsindoorssdk:3.3.1.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@devDebugAndroidTest/compileClasspath': Could not resolve com.mapspeople.mapsindoors:mapsindoorssdk:3.3.1.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@devDebugUnitTest/compileClasspath': Could not resolve com.mapspeople.mapsindoors:mapsindoorssdk:3.3.1.
> Show Details
> Affected Modules: app
> 

what do i do ?

it also has this maven in its repositories.
    repositories {
        maven {
            url 'http://maven.mapsindoors.com/'
        }

tnx

**Comment by namine92** [comment]
Hi @NimaaZx , are you by chance behind a firewall?

**Comment by NimaaZx** [comment]
tnx for replay. internet is censored in my country and Boycott by some U.S companies. but I use OpenVpn Connection. I need your recommendation for my project. can you give me your email Address? I see you are working on Indoor map.

**Comment by namine92** [comment]
@NimaaZx if you have any questions please ask it here, or rather make a new issue with your question.

**Comment by NimaaZx** [comment]
@namine92 ok, thank you. I could run the app. problem was define network settings in gradle.properties(global properties). but I have another problem.  how can this app should work? when I run it map view shows blank. 
I also add my api map key as :

`	<string name="google_maps_key">AIzaSyDjaB1K_tp******ohA67le9zLrUh0WPw4</string>
`
in my res/values/strings.xml

is it related to my country location or key problem? I used vpn in my phone but nothing is changed.
as i mention i live in iran.

**Comment by namine92** [comment]
it can be any of those tow, but in which country are you? because google APIs don't work in certain countries?

**Comment by NimaaZx** [comment]
> it can be any of those tow, but in which country are you? because google APIs don't work in certain countries?

As i mention I live in iran, middle east. but why is not working using vpn !!?

**Comment by namine92** [comment]
@NimaaZx I think you should contact google support for this to get the API working, What I can help you with is check that the google maps api is enabled for your key in the google console : https://console.cloud.google.com/

**Comment by NimaaZx** [comment]
thanks again. good luck
